Repository kakao-tech-campus-2nd-step3/Team8_BE, pull requests merged in 2024-10, with the labels that each got.

#31 Feat: 보호자용 마이페이지와 관련된 로직 구현
  src/main/java/com/example/sinitto/guard/controller/GuardController.java
  src/main/java/com/example/sinitto/guard/controller/GuardControllerAdvice.java
  src/main/java/com/example/sinitto/guard/exception/SeniorNotFoundException.java
  src/main/java/com/example/sinitto/guard/repository/SeniorRepository.java
  src/main/java/com/example/sinitto/guard/service/GuardService.java
  src/main/java/com/example/sinitto/member/entity/Member.java
  src/main/java/com/example/sinitto/member/entity/Senior.java
  src/main/java/com/example/sinitto/member/repository/MemberRepository.java
  src/test/java/com/example/sinitto/guard/entity/SeniorTest.java
  src/test/java/com/example/sinitto/guard/repository/SeniorRepositoryTest.java
Labels: ✨ Feature, ♻️ Refactoring

#32 Feat: 콜백서비스 기능 구현
  build.gradle
  src/main/java/com/example/sinitto/callback/controller/CallbackController.java
  src/main/java/com/example/sinitto/callback/controller/CallbackControllerAdvice.java
  src/main/java/com/example/sinitto/callback/dto/CallbackResponse.java
  src/main/java/com/example/sinitto/callback/entity/Callback.java
  src/main/java/com/example/sinitto/callback/exception/AlreadyCompleteException.java
  src/main/java/com/example/sinitto/callback/exception/AlreadyInProgressException.java
  src/main/java/com/example/sinitto/callback/exception/AlreadyWaitingException.java
  src/main/java/com/example/sinitto/callback/exception/ConflictException.java
  src/main/java/com/example/sinitto/callback/exception/ForbiddenException.java
  src/main/java/com/example/sinitto/callback/exception/NotAssignedException.java
  src/main/java/com/example/sinitto/callback/exception/NotSinittoException.java
  src/main/java/com/example/sinitto/callback/repository/CallbackRepository.java
  src/main/java/com/example/sinitto/callback/service/CallbackService.java
  src/main/java/com/example/sinitto/callback/util/TwilioHelper.java
  src/main/java/com/example/sinitto/guard/repository/SeniorRepository.java
  src/test/java/com/example/sinitto/callback/entity/CallbackTest.java
  src/test/java/com/example/sinitto/callback/service/CallbackServiceTest.java
  src/test/java/com/example/sinitto/callback/util/TwilioHelperTest.java
Labels: ✨ Feature

#35 Feat: Swagger에서 JWT 활용 기능 활성화
  src/main/java/com/example/sinitto/auth/controller/AuthController.java
  src/main/java/com/example/sinitto/common/annotation/MemberId.java
  src/main/java/com/example/sinitto/common/config/SwaggerConfig.java
  src/main/java/com/example/sinitto/member/controller/MemberController.java
Labels: ✨ Feature

#36 Feat: 시니또용 마이페이지와 관련된 로직 및 테스트 코드 구현
  src/main/java/com/example/sinitto/member/entity/Sinitto.java
  src/main/java/com/example/sinitto/sinitto/controller/SinittoController.java
  src/main/java/com/example/sinitto/sinitto/controller/SinittoControllerAdvice.java
  src/main/java/com/example/sinitto/sinitto/dto/SinittoBankRequest.java
  src/main/java/com/example/sinitto/sinitto/dto/SinittoBankResponse.java
  src/main/java/com/example/sinitto/sinitto/exception/SinittoNotFoundException.java
  src/main/java/com/example/sinitto/sinitto/repository/SinittoRepository.java
  src/main/java/com/example/sinitto/sinitto/service/SinittoService.java
  src/test/java/com/example/sinitto/sinitto/entity/SinittoTest.java
  src/test/java/com/example/sinitto/sinitto/repository/SinittoRepositoryTest.java
Labels: ✨ Feature, ✅ Test Code

#37 Feat: 로그인 로직에서 프론트에 보내는 DTO에 status 추가 및 리프레쉬 토큰 서버 관리 로직 구현 (멘토링 코멘트 적용)
  .gitignore
  build.gradle
  src/main/java/com/example/sinitto/auth/dto/LoginResponse.java
  src/main/java/com/example/sinitto/auth/service/TokenService.java
  src/main/java/com/example/sinitto/guard/controller/GuardController.java
  src/main/java/com/example/sinitto/guard/controller/GuardControllerAdvice.java
  src/main/java/com/example/sinitto/guard/repository/SeniorRepository.java
  src/main/java/com/example/sinitto/guard/service/GuardService.java
  src/main/java/com/example/sinitto/member/entity/Member.java
  src/main/java/com/example/sinitto/member/entity/Senior.java
  src/main/java/com/example/sinitto/member/repository/MemberRepository.java
  src/main/java/com/example/sinitto/member/service/MemberService.java
  src/main/java/com/example/sinitto/sinitto/controller/SinittoController.java
  src/main/java/com/example/sinitto/sinitto/controller/SinittoControllerAdvice.java
  src/main/java/com/example/sinitto/sinitto/exception/SinittoNotFoundException.java
  src/main/java/com/example/sinitto/sinitto/repository/SinittoRepository.java
  src/main/java/com/example/sinitto/sinitto/service/SinittoService.java
  src/main/resources/application.properties
  src/test/java/com/example/sinitto/guard/entity/SeniorTest.java
  src/test/java/com/example/sinitto/guard/repository/SeniorRepositoryTest.java
Labels: ✨ Feature, ♻️ Refactoring

#41 Feat : 리뷰 기능과 관련된 로직 구현 #38
  src/main/java/com/example/sinitto/member/entity/Senior.java
  src/main/java/com/example/sinitto/review/controller/ReviewController.java
  src/main/java/com/example/sinitto/review/dto/ReviewRequest.java
  src/main/java/com/example/sinitto/review/dto/ReviewResponse.java
  src/main/java/com/example/sinitto/review/entity/Review.java
  src/main/java/com/example/sinitto/review/repository/ReviewRepository.java
  src/main/java/com/example/sinitto/review/service/ReviewService.java
  src/test/java/com/example/sinitto/review/entity/ReviewTest.java
  src/test/java/com/example/sinitto/review/service/ReviewServiceTest.java
Labels: ✨ Feature, ♻️ Refactoring

#49 Feat: 완료 대기 상태 추가 그리고 특정 시니또가 진행 중인 콜백 조회 기능
  src/main/java/com/example/sinitto/callback/controller/CallbackController.java
  src/main/java/com/example/sinitto/callback/controller/CallbackControllerAdvice.java
  src/main/java/com/example/sinitto/callback/entity/Callback.java
  src/main/java/com/example/sinitto/callback/exception/AlreadyPendingCompleteException.java
  src/main/java/com/example/sinitto/callback/exception/GuardMismatchException.java
  src/main/java/com/example/sinitto/callback/exception/NotExistCallbackException.java
  src/main/java/com/example/sinitto/callback/exception/NotFoundException.java
  src/main/java/com/example/sinitto/callback/exception/NotMemberException.java
  src/main/java/com/example/sinitto/callback/repository/CallbackRepository.java
  src/main/java/com/example/sinitto/callback/service/CallbackService.java
  src/test/java/com/example/sinitto/callback/entity/CallbackTest.java
  src/test/java/com/example/sinitto/callback/repository/CallbackRepositoryTest.java
  src/test/java/com/example/sinitto/callback/service/CallbackServiceTest.java
Labels: ✨ Feature, ♻️ Refactoring

#52 Refactor: 2차 멘토링 코멘트 반영
  src/main/java/com/example/sinitto/auth/controller/AuthControllerAdvice.java
  src/main/java/com/example/sinitto/auth/dto/KakaoTokenResponse.java
  src/main/java/com/example/sinitto/auth/entity/KakaoToken.java
  src/main/java/com/example/sinitto/auth/exception/KakaoEmailNotFoundException.java
  src/main/java/com/example/sinitto/auth/service/KakaoApiService.java
  src/main/java/com/example/sinitto/common/config/RestTemplateResponseErrorHandler.java
  src/main/java/com/example/sinitto/common/config/WebConfig.java
  src/main/java/com/example/sinitto/member/controller/MemberController.java
  src/main/java/com/example/sinitto/member/dto/RegisterResponse.java
  src/main/java/com/example/sinitto/member/service/MemberService.java
Labels: ♻️ Refactoring

#56 Deploy: 자동 배포 로직(CI) 구현
  .github/workflows/deploy.yml
Labels: 🚀 Deploy

#58 Fix: 레디스 비밀번호 추가 구현
  src/main/resources/application.properties
Labels: 😡 Bug Fix

#54 Feat: 포인트 기능
  build.gradle
  src/main/java/com/example/sinitto/callback/service/CallbackService.java
  src/main/java/com/example/sinitto/helloCall/service/HelloCallService.java
  src/main/java/com/example/sinitto/member/entity/Member.java
  src/main/java/com/example/sinitto/member/service/MemberService.java
  src/main/java/com/example/sinitto/point/controller/PointAdminController.java
  src/main/java/com/example/sinitto/point/controller/PointAdminControllerAdvice.java
  src/main/java/com/example/sinitto/point/controller/PointController.java
  src/main/java/com/example/sinitto/point/controller/PointControllerAdvice.java
  src/main/java/com/example/sinitto/point/dto/PointChargeResponse.java
  src/main/java/com/example/sinitto/point/dto/PointLogResponse.java
  src/main/java/com/example/sinitto/point/dto/PointLogWithBankInfo.java
  src/main/java/com/example/sinitto/point/dto/PointLogWithDepositMessage.java
  src/main/java/com/example/sinitto/point/dto/PointRequest.java
  src/main/java/com/example/sinitto/point/dto/PointResponse.java
  src/main/java/com/example/sinitto/point/entity/Point.java
  src/main/java/com/example/sinitto/point/entity/PointLog.java
  src/main/java/com/example/sinitto/point/exception/InvalidPointLogStatusException.java
  src/main/java/com/example/sinitto/point/exception/NotEnoughPointException.java
  src/main/java/com/example/sinitto/point/exception/PointLogNotFoundException.java
  src/main/java/com/example/sinitto/point/exception/PointNotFoundException.java
  src/main/java/com/example/sinitto/point/repository/PointLogRepository.java
  src/main/java/com/example/sinitto/point/repository/PointRepository.java
  src/main/java/com/example/sinitto/point/service/PointAdminService.java
  src/main/java/com/example/sinitto/point/service/PointService.java
  src/main/resources/static/css/point.css
  src/main/resources/templates/point/charge.html
  src/main/resources/templates/point/withdraw.html
  src/test/java/com/example/sinitto/callback/service/CallbackServiceTest.java
  src/test/java/com/example/sinitto/point/entity/PointLogTest.java
  src/test/java/com/example/sinitto/point/entity/PointTest.java
  src/test/java/com/example/sinitto/point/service/PointServiceTest.java
Labels: ✨ Feature

#67 Deploy: 더미 데이터 추가 완료
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
Labels: 🚀 Deploy

#69 Deploy: 안부전화 더미데이터 추가 구현 (프론트 요청)
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
Labels: 🚀 Deploy

#64 Feat: 콜백 서비스 정책 적용 그리고 이용 내역 조회 기능
  src/main/java/com/example/sinitto/SinittoApplication.java
  src/main/java/com/example/sinitto/callback/controller/CallbackController.java
  src/main/java/com/example/sinitto/callback/dto/CallbackUsageHistoryResponse.java
  src/main/java/com/example/sinitto/callback/entity/Callback.java
  src/main/java/com/example/sinitto/callback/exception/MemberHasInProgressCallbackException.java
  src/main/java/com/example/sinitto/callback/repository/CallbackRepository.java
  src/main/java/com/example/sinitto/callback/service/CallbackService.java
  src/main/java/com/example/sinitto/guard/repository/SeniorRepository.java
  src/main/java/com/example/sinitto/point/controller/PointAdminController.java
  src/main/java/com/example/sinitto/point/entity/Point.java
  src/test/java/com/example/sinitto/callback/entity/CallbackTest.java
  src/test/java/com/example/sinitto/callback/repository/CallbackRepositoryTest.java
  src/test/java/com/example/sinitto/callback/service/CallbackServiceTest.java
Labels: ✨ Feature

#74 Feat: 스웨거 기본값 추가 구현 (안부전화 파트)
  src/main/java/com/example/sinitto/helloCall/controller/HelloCallController.java
  src/main/java/com/example/sinitto/helloCall/dto/HelloCallDetailResponse.java
  src/main/java/com/example/sinitto/helloCall/dto/HelloCallDetailUpdateRequest.java
  src/main/java/com/example/sinitto/helloCall/dto/HelloCallPriceRequest.java
  src/main/java/com/example/sinitto/helloCall/dto/HelloCallRequest.java
  src/main/java/com/example/sinitto/helloCall/service/HelloCallService.java
Labels: ✨ Feature

#75 Feat: 이미 진행중 or 대기중 인 콜백이 있으면 추가적인 콜백 생성 안되게 함
  src/main/java/com/example/sinitto/callback/controller/CallbackController.java
  src/main/java/com/example/sinitto/callback/repository/CallbackRepository.java
  src/main/java/com/example/sinitto/callback/service/CallbackService.java
  src/main/resources/templates/point/withdraw.html
  src/test/java/com/example/sinitto/callback/repository/CallbackRepositoryTest.java
  src/test/java/com/example/sinitto/callback/service/CallbackServiceTest.java
Labels: ✨ Feature, ✅ Test Code, ♻️ Refactoring

#71 Refactor: 3차 리뷰 수정사항 적용 구현 (안부전화, 카카오API 관련)
  build.gradle
  src/main/java/com/example/sinitto/auth/dto/KakaoTokenResponse.java
  src/main/java/com/example/sinitto/common/config/WebConfig.java
  src/main/java/com/example/sinitto/helloCall/dto/HelloCallDetailResponse.java
  src/main/java/com/example/sinitto/helloCall/dto/HelloCallDetailUpdateRequest.java
  src/main/java/com/example/sinitto/helloCall/dto/HelloCallPriceRequest.java
  src/main/java/com/example/sinitto/helloCall/dto/HelloCallRequest.java
  src/main/java/com/example/sinitto/helloCall/entity/HelloCall.java
  src/main/java/com/example/sinitto/helloCall/repository/HelloCallTimeLogRepository.java
  src/main/java/com/example/sinitto/helloCall/service/HelloCallService.java
  src/test/java/com/example/sinitto/hellocall/entity/HelloCallTest.java
  src/test/java/com/example/sinitto/hellocall/repository/HelloCallTimeLogRepositoryTest.java
Labels: ✨ Feature, ♻️ Refactoring

#85 Deploy: 포인트 로그 더미데이터 추가(프론트 요청)
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
  src/main/java/com/example/sinitto/point/entity/PointLog.java
Labels: 🚀 Deploy

#89 Refactor: 시니또 은행정보 처리 로직 변경, 안부전화 시니또 저장계층 member로 변경, 은행정보 없을 경우 예외처리 구현
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
  src/main/java/com/example/sinitto/helloCall/controller/HelloCallController.java
  src/main/java/com/example/sinitto/helloCall/dto/HelloCallTimeResponse.java
  src/main/java/com/example/sinitto/helloCall/entity/HelloCall.java
  src/main/java/com/example/sinitto/helloCall/entity/HelloCallTimeLog.java
  src/main/java/com/example/sinitto/helloCall/repository/HelloCallRepository.java
  src/main/java/com/example/sinitto/helloCall/repository/HelloCallTimeLogRepository.java
  src/main/java/com/example/sinitto/helloCall/service/HelloCallService.java
  src/main/java/com/example/sinitto/point/service/PointAdminService.java
  src/main/java/com/example/sinitto/point/service/PointService.java
  src/main/java/com/example/sinitto/sinitto/controller/SinittoControllerAdvice.java
  src/main/java/com/example/sinitto/sinitto/entity/SinittoBankInfo.java
  src/main/java/com/example/sinitto/sinitto/exception/SinittoBankInfoNotFoundException.java
  src/main/java/com/example/sinitto/sinitto/exception/SinittoNotFoundException.java
  src/main/java/com/example/sinitto/sinitto/repository/SinittoBankInfoRepository.java
  src/main/java/com/example/sinitto/sinitto/service/SinittoService.java
  src/test/java/com/example/sinitto/hellocall/entity/HelloCallTimeLogTest.java
  src/test/java/com/example/sinitto/hellocall/repository/HelloCallRepositoryTest.java
  src/test/java/com/example/sinitto/hellocall/repository/HelloCallTimeLogRepositoryTest.java
  src/test/java/com/example/sinitto/member/entity/MemberTest.java
  src/test/java/com/example/sinitto/sinitto/entity/SinittoBankInfoTest.java
  src/test/java/com/example/sinitto/sinitto/entity/SinittoTest.java
  src/test/java/com/example/sinitto/sinitto/repository/SinittoBankInfoRepositoryTest.java
  src/test/java/com/example/sinitto/sinitto/repository/SinittoRepositoryTest.java
Labels: ♻️ Refactoring

#94 Deploy: PR 생성시 테스트코드 수행 로직 구현
  .github/workflows/testcode.yml
  src/test/java/com/example/sinitto/SinittoApplicationTests.java
Labels: 🚀 Deploy

#96 Deploy: 깃허브 액션 최신버전으로 업그레이드
  .github/workflows/deploy.yml
  .github/workflows/testcode.yml
Labels: 🚀 Deploy

#100 Fix: 안부전화 Cascade 순환참조 문제 해결 및 관계성 오류 해결 구현
  src/main/java/com/example/sinitto/helloCall/entity/HelloCall.java
  src/main/java/com/example/sinitto/helloCall/entity/HelloCallTimeLog.java
  src/main/java/com/example/sinitto/helloCall/entity/TimeSlot.java
Labels: 🚑 HotFix!

#103 Refactor: 가이드라인 관련 로직 수정 {프론트 요청)
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
  src/main/java/com/example/sinitto/guardGuideline/controller/GuardGuidelineController.java
  src/main/java/com/example/sinitto/guardGuideline/dto/GuardGuidelineRequest.java
  src/main/java/com/example/sinitto/guardGuideline/dto/GuardGuidelineResponse.java
  src/main/java/com/example/sinitto/guardGuideline/exception/GuardGuidelineNotFoundException.java
  src/main/java/com/example/sinitto/guardGuideline/exception/SeniorAndGuardGuidelineMismatchException.java
  src/main/java/com/example/sinitto/guardGuideline/service/GuardGuidelineService.java
Labels: ♻️ Refactoring

#106 fix: url 중복 오류해결
  src/main/java/com/example/sinitto/guardGuideline/controller/GuardGuidelineController.java
Labels: 😡 Bug Fix

#104 Feat: 콜백 단건조회 api 응답값에 boolean isAssignedToSelf, String seniorPhoneNumber 추가
  src/main/java/com/example/sinitto/callback/controller/CallbackController.java
  src/main/java/com/example/sinitto/callback/dto/CallbackForSinittoResponse.java
  src/main/java/com/example/sinitto/callback/service/CallbackService.java
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
  src/test/java/com/example/sinitto/callback/service/CallbackServiceTest.java
Labels: ✨ Feature

#113 Deploy: 더미데이터 실행 과정 중 initial()과 saveRefreshTokenToRedis() 메서드 실행을 별도의 트랜잭션으로 관리
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
Labels: 🚀 Deploy

#117 Deploy: 할당되는 콜백 더미 데이터에 각각 `callbackRepository.save(callback{id});` 추가
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
Labels: 🚀 Deploy

#114 Feat: 시니또용 카테고리별 가이드라인 조회 api 추가 및 기존 api 삭제 (프론트 요청)
  src/main/java/com/example/sinitto/guardGuideline/controller/GuardGuidelineController.java
  src/main/java/com/example/sinitto/guardGuideline/service/GuardGuidelineService.java
Labels: ✨ Feature, ♻️ Refactoring

#120 Deploy: 로컬과 개발 환경에 따라 카카오 리다이렉트 주소를 다르게 리턴하는 로직 구현
  src/main/java/com/example/sinitto/auth/controller/AuthController.java
  src/main/java/com/example/sinitto/auth/service/KakaoApiService.java
  src/main/java/com/example/sinitto/common/properties/KakaoProperties.java
  src/main/java/com/example/sinitto/member/service/MemberService.java
Labels: 🚀 Deploy, ✨ Feature

#122 카카오 로그인 요청 헤더 추출 로직에서 NULL 예외처리 구현
  src/main/java/com/example/sinitto/auth/service/KakaoApiService.java
Labels: 😡 Bug Fix

#123 Feat: 콜백 단건 조회 로직 개선
  src/main/java/com/example/sinitto/callback/service/CallbackService.java
  src/test/java/com/example/sinitto/callback/service/CallbackServiceTest.java
Labels: ✨ Feature

#128 더미데이터로 로그인 기능 SSR로 구현
  src/main/java/com/example/sinitto/SinittoApplication.java
  src/main/java/com/example/sinitto/common/properties/DummyProperties.java
  src/main/java/com/example/sinitto/member/controller/MemberAdminController.java
  src/main/java/com/example/sinitto/member/repository/MemberRepository.java
  src/main/resources/static/css/dummy.css
  src/main/resources/templates/dummy/login.html
  src/test/java/com/example/sinitto/member/repository/MemberRepositoryTest.java
Labels: 🚀 Deploy, ✨ Feature

#126 Feat: 시니또 회원 정보와 계좌 정보 조회 API 및 로직 분리
  src/main/java/com/example/sinitto/guard/dto/GuardRequest.java
  src/main/java/com/example/sinitto/guard/service/GuardService.java
  src/main/java/com/example/sinitto/member/entity/Member.java
  src/main/java/com/example/sinitto/sinitto/controller/SinittoController.java
  src/main/java/com/example/sinitto/sinitto/dto/SinittoRequest.java
  src/main/java/com/example/sinitto/sinitto/dto/SinittoResponse.java
  src/main/java/com/example/sinitto/sinitto/service/SinittoService.java
  src/test/java/com/example/sinitto/member/entity/MemberTest.java
Labels: ✨ Feature, ♻️ Refactoring

#130 Fix: 더미데이터 로그인 SSR input창 좌우여백 조정
  src/main/resources/static/css/dummy.css
Labels: 😡 Bug Fix
