Repository kakao-tech-campus-2nd-step3/Team8_BE, pull requests merged in 2024-09, with the labels that each got.

#3 Feat: 팀원 모두 참여한 초기 Swagger
  .gitignore
  src/main/java/com/example/sinitto/SinittoApplication.java
  src/main/java/com/example/sinitto/config/SwaggerConfig.java
  src/main/java/com/example/sinitto/controller/AuthController.java
  src/main/java/com/example/sinitto/controller/CallbackController.java
  src/main/java/com/example/sinitto/controller/GuardController.java
  src/main/java/com/example/sinitto/controller/GuardGuidelineController.java
  src/main/java/com/example/sinitto/controller/HelloCallController.java
  src/main/java/com/example/sinitto/controller/MemberController.java
  src/main/java/com/example/sinitto/controller/PointController.java
  src/main/java/com/example/sinitto/controller/ReviewController.java
  src/main/java/com/example/sinitto/controller/SinittoController.java
  src/main/java/com/example/sinitto/dto/CallbackResponse.java
  src/main/java/com/example/sinitto/dto/GuardGuidelineRequest.java
  src/main/java/com/example/sinitto/dto/GuardGuidelineResponse.java
  src/main/java/com/example/sinitto/dto/GuardRequest.java
  src/main/java/com/example/sinitto/dto/GuardResponse.java
  src/main/java/com/example/sinitto/dto/GuardSignupRequest.java
  src/main/java/com/example/sinitto/dto/HelloCallDetailResponse.java
  src/main/java/com/example/sinitto/dto/HelloCallReportRequest.java
  src/main/java/com/example/sinitto/dto/HelloCallRequest.java
  src/main/java/com/example/sinitto/dto/HelloCallResponse.java
  src/main/java/com/example/sinitto/dto/PointLogResponse.java
  src/main/java/com/example/sinitto/dto/PointRequest.java
  src/main/java/com/example/sinitto/dto/PointResponse.java
  src/main/java/com/example/sinitto/dto/ReviewRequest.java
  src/main/java/com/example/sinitto/dto/ReviewResponse.java
  src/main/java/com/example/sinitto/dto/SeniorRequest.java
  src/main/java/com/example/sinitto/dto/SeniorResponse.java
  src/main/java/com/example/sinitto/dto/SinittoGuidelineRequest.java
  src/main/java/com/example/sinitto/dto/SinittoGuidelineResponse.java
  src/main/java/com/example/sinitto/dto/SinittoRequest.java
  src/main/java/com/example/sinitto/dto/SinittoResponse.java
  src/main/java/com/example/sinitto/dto/SinittoSignupRequest.java
  src/main/java/com/example/sinitto/dto/TokenRefreshRequest.java
  src/main/java/com/example/sinitto/dto/TokenResponse.java
  src/main/resources/application.properties
  src/test/java/com/example/sinitto/SinittoApplicationTests.java
Labels: 📡 API

#4 Feat: 팀원 모두 참여한 초기 Swagger(Weekly->Develop)
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/sinitto/SinittoApplication.java
  src/main/java/com/example/sinitto/config/SwaggerConfig.java
  src/main/java/com/example/sinitto/controller/AuthController.java
  src/main/java/com/example/sinitto/controller/CallbackController.java
  src/main/java/com/example/sinitto/controller/GuardController.java
  src/main/java/com/example/sinitto/controller/GuardGuidelineController.java
  src/main/java/com/example/sinitto/controller/HelloCallController.java
  src/main/java/com/example/sinitto/controller/MemberController.java
  src/main/java/com/example/sinitto/controller/PointController.java
  src/main/java/com/example/sinitto/controller/ReviewController.java
  src/main/java/com/example/sinitto/controller/SinittoController.java
  src/main/java/com/example/sinitto/dto/CallbackResponse.java
  src/main/java/com/example/sinitto/dto/GuardGuidelineRequest.java
  src/main/java/com/example/sinitto/dto/GuardGuidelineResponse.java
  src/main/java/com/example/sinitto/dto/GuardRequest.java
  src/main/java/com/example/sinitto/dto/GuardResponse.java
  src/main/java/com/example/sinitto/dto/GuardSignupRequest.java
  src/main/java/com/example/sinitto/dto/HelloCallDetailResponse.java
  src/main/java/com/example/sinitto/dto/HelloCallReportRequest.java
  src/main/java/com/example/sinitto/dto/HelloCallRequest.java
  src/main/java/com/example/sinitto/dto/HelloCallResponse.java
  src/main/java/com/example/sinitto/dto/PointLogResponse.java
  src/main/java/com/example/sinitto/dto/PointRequest.java
  src/main/java/com/example/sinitto/dto/PointResponse.java
  src/main/java/com/example/sinitto/dto/ReviewRequest.java
  src/main/java/com/example/sinitto/dto/ReviewResponse.java
  src/main/java/com/example/sinitto/dto/SeniorRequest.java
  src/main/java/com/example/sinitto/dto/SeniorResponse.java
  src/main/java/com/example/sinitto/dto/SinittoGuidelineRequest.java
  src/main/java/com/example/sinitto/dto/SinittoGuidelineResponse.java
  src/main/java/com/example/sinitto/dto/SinittoRequest.java
  src/main/java/com/example/sinitto/dto/SinittoResponse.java
  src/main/java/com/example/sinitto/dto/SinittoSignupRequest.java
  src/main/java/com/example/sinitto/dto/TokenRefreshRequest.java
  src/main/java/com/example/sinitto/dto/TokenResponse.java
  src/main/resources/application.properties
  src/test/java/com/example/sinitto/SinittoApplicationTests.java
Labels: 📡 API

#11 Refactor: class DTO를 record DTO로 수정
  src/main/java/com/example/sinitto/controller/CallbackController.java
  src/main/java/com/example/sinitto/controller/GuardController.java
  src/main/java/com/example/sinitto/controller/GuardGuidelineController.java
  src/main/java/com/example/sinitto/controller/HelloCallController.java
  src/main/java/com/example/sinitto/controller/PointController.java
  src/main/java/com/example/sinitto/controller/SinittoController.java
  src/main/java/com/example/sinitto/dto/CallbackResponse.java
  src/main/java/com/example/sinitto/dto/GuardGuidelineRequest.java
  src/main/java/com/example/sinitto/dto/GuardGuidelineResponse.java
  src/main/java/com/example/sinitto/dto/GuardRequest.java
  src/main/java/com/example/sinitto/dto/GuardResponse.java
  src/main/java/com/example/sinitto/dto/GuardSignupRequest.java
  src/main/java/com/example/sinitto/dto/HelloCallDetailResponse.java
  src/main/java/com/example/sinitto/dto/HelloCallReportRequest.java
  src/main/java/com/example/sinitto/dto/HelloCallRequest.java
  src/main/java/com/example/sinitto/dto/HelloCallResponse.java
  src/main/java/com/example/sinitto/dto/PointLogResponse.java
  src/main/java/com/example/sinitto/dto/PointRequest.java
  src/main/java/com/example/sinitto/dto/PointResponse.java
  src/main/java/com/example/sinitto/dto/ReviewRequest.java
  src/main/java/com/example/sinitto/dto/ReviewResponse.java
  src/main/java/com/example/sinitto/dto/SeniorRequest.java
  src/main/java/com/example/sinitto/dto/SeniorResponse.java
  src/main/java/com/example/sinitto/dto/SinittoGuidelineRequest.java
  src/main/java/com/example/sinitto/dto/SinittoGuidelineResponse.java
  src/main/java/com/example/sinitto/dto/SinittoRequest.java
  src/main/java/com/example/sinitto/dto/SinittoResponse.java
  src/main/java/com/example/sinitto/dto/SinittoSignupRequest.java
  src/main/java/com/example/sinitto/dto/TokenRefreshRequest.java
  src/main/java/com/example/sinitto/dto/TokenResponse.java
Labels: ♻️ Refactoring

#13 Feat: MemberId위한 MethodArgumentResolver 구현
  src/main/java/com/example/sinitto/common/annotation/MemberId.java
  src/main/java/com/example/sinitto/common/config/WebConfig.java
  src/main/java/com/example/sinitto/common/resolver/MemberIdArgumentResolver.java
Labels: ✨ Feature

#15 Feat: 초기 Entity 구현
  src/main/java/com/example/sinitto/SinittoApplication.java
  src/main/java/com/example/sinitto/callback/entity/Callback.java
  src/main/java/com/example/sinitto/guardGuideline/entity/GuardGuideLine.java
  src/main/java/com/example/sinitto/member/entity/Member.java
  src/main/java/com/example/sinitto/member/entity/Senior.java
  src/main/java/com/example/sinitto/member/entity/Sinitto.java
  src/main/java/com/example/sinitto/point/entity/Point.java
  src/main/java/com/example/sinitto/point/entity/PointLog.java
Labels: ✨ Feature

#29 Feat: Resolver JWT 데이터 추출 로직 추가, 카카오 로그인 및 JWT 로직 구현
  .gitignore
  build.gradle
  src/main/java/com/example/sinitto/SinittoApplication.java
  src/main/java/com/example/sinitto/auth/controller/AuthController.java
  src/main/java/com/example/sinitto/auth/controller/AuthControllerAdvice.java
  src/main/java/com/example/sinitto/auth/dto/KakaoTokenResponse.java
  src/main/java/com/example/sinitto/auth/dto/KakaoUserResponse.java
  src/main/java/com/example/sinitto/auth/dto/LoginResponse.java
  src/main/java/com/example/sinitto/auth/dto/RegisterResponse.java
  src/main/java/com/example/sinitto/auth/dto/TokenRefreshRequest.java
  src/main/java/com/example/sinitto/auth/dto/TokenResponse.java
  src/main/java/com/example/sinitto/auth/entity/KakaoToken.java
  src/main/java/com/example/sinitto/auth/exception/JWTExpirationException.java
  src/main/java/com/example/sinitto/auth/exception/KakaoRefreshTokenExpirationException.java
  src/main/java/com/example/sinitto/auth/exception/TokenNotFoundException.java
  src/main/java/com/example/sinitto/auth/exception/UnauthorizedException.java
  src/main/java/com/example/sinitto/auth/repository/KakaoTokenRepository.java
  src/main/java/com/example/sinitto/auth/service/KakaoApiService.java
  src/main/java/com/example/sinitto/auth/service/KakaoTokenService.java
  src/main/java/com/example/sinitto/auth/service/TokenService.java
  src/main/java/com/example/sinitto/common/config/ArgumentResolverConfig.java
  src/main/java/com/example/sinitto/common/config/WebConfig.java
  src/main/java/com/example/sinitto/common/properties/KakaoProperties.java
  src/main/java/com/example/sinitto/common/resolver/MemberIdArgumentResolver.java
  src/main/java/com/example/sinitto/common/resolver/MemberIdProvider.java
  src/main/java/com/example/sinitto/member/controller/MemberController.java
  src/main/java/com/example/sinitto/member/controller/MemberControllerAdvice.java
  src/main/java/com/example/sinitto/member/dto/GuardSignupRequest.java
  src/main/java/com/example/sinitto/member/dto/SignupRequest.java
  src/main/java/com/example/sinitto/member/entity/Member.java
  src/main/java/com/example/sinitto/member/exception/MemberNotFoundException.java
  src/main/java/com/example/sinitto/member/exception/NotUniqueException.java
  src/main/java/com/example/sinitto/member/repository/MemberRepository.java
  src/main/java/com/example/sinitto/member/service/MemberService.java
  src/main/resources/application.properties
  src/test/java/com/example/sinitto/auth/entity/KakaoTokenTest.java
  src/test/java/com/example/sinitto/auth/repository/KakaoTokenRepositoryTest.java
  src/test/java/com/example/sinitto/member/entity/MemberTest.java
  src/test/java/com/example/sinitto/member/repository/MemberRepositoryTest.java
Labels: ✨ Feature, ♻️ Refactoring
