Repository kakao-tech-campus-2nd-step3/Team8_BE, pull requests merged in 2024-11, with the labels that each got.

#139 Fix, Refactor : refreshToken 만료 시 InvalidJwtException 반환하도록 변경, accessToken의 만료 시간 수정
  src/main/java/com/example/sinitto/auth/service/KakaoTokenService.java
  src/main/java/com/example/sinitto/auth/service/TokenService.java
Labels: 😡 Bug Fix, ♻️ Refactoring

#143 Feat: helloCallDetailResponse에 ServiceTime 필드 추가 (프론트 요청)
  src/main/java/com/example/sinitto/helloCall/dto/HelloCallDetailResponse.java
  src/main/java/com/example/sinitto/helloCall/service/HelloCallService.java
Labels: ✨ Feature

#141 Refactor: 카카오 DTO 4차 코드리뷰 반영
  src/main/java/com/example/sinitto/auth/dto/KakaoTokenResponse.java
Labels: ♻️ Refactoring

#131 Feat : 각 도메인별 테스트 코드 추가 및 수정 및 각 멤버 별(보호자, 시니또) 할 수 있는 행동 제약 추가
  src/main/java/com/example/sinitto/auth/service/TokenService.java
  src/main/java/com/example/sinitto/guard/service/GuardService.java
  src/main/java/com/example/sinitto/sinitto/controller/SinittoController.java
  src/main/java/com/example/sinitto/sinitto/service/SinittoService.java
  src/test/java/com/example/sinitto/auth/service/KakaoApiServiceTest.java
  src/test/java/com/example/sinitto/auth/service/KakaoTokenServiceTest.java
  src/test/java/com/example/sinitto/auth/service/TokenServiceTest.java
  src/test/java/com/example/sinitto/guard/service/GuardServiceTest.java
  src/test/java/com/example/sinitto/guardGuideline/service/GuardGuildelineServiceTest.java
  src/test/java/com/example/sinitto/hellocall/service/HelloCallServiceTest.java
  src/test/java/com/example/sinitto/member/service/MemberServiceTest.java
  src/test/java/com/example/sinitto/sinitto/service/SinittoServiceTest.java
Labels: ✨ Feature, ✅ Test Code, ♻️ Refactoring

#144 Refactor: 포인트 도메인 운영코드 개선과 테스트코드 개선 및 추가
  src/main/java/com/example/sinitto/point/controller/PointAdminController.java
  src/main/java/com/example/sinitto/point/dto/PointLogWithBankInfo.java
  src/main/java/com/example/sinitto/point/dto/PointLogWithDepositMessage.java
  src/main/java/com/example/sinitto/point/entity/PointLog.java
  src/main/java/com/example/sinitto/point/service/PointAdminService.java
  src/main/java/com/example/sinitto/point/service/PointService.java
  src/main/resources/static/css/point.css
  src/main/resources/templates/point/charge.html
  src/main/resources/templates/point/withdraw.html
  src/test/java/com/example/sinitto/point/service/PointAdminServiceTest.java
  src/test/java/com/example/sinitto/point/service/PointServiceTest.java
Labels: ✅ Test Code, ♻️ Refactoring

#146 Deploy: 무중단 배포 구현 중 health check를 위한 dependency 추가
  build.gradle
Labels: 🚀 Deploy

#148 Fix: 배포 과정중 dependency 에러처리
  build.gradle
Labels: 😡 Bug Fix, 🚀 Deploy

#152 HotFix: 토큰 보안로직 추가 구현
  src/main/java/com/example/sinitto/auth/service/TokenService.java
  src/main/java/com/example/sinitto/member/service/MemberService.java
  src/test/java/com/example/sinitto/auth/service/TokenServiceTest.java
  src/test/java/com/example/sinitto/hellocall/service/HelloCallServiceTest.java
  src/test/java/com/example/sinitto/member/service/MemberServiceTest.java
Labels: 🚑 HotFix!

#132 Refactor: 포인트관련 로직을 포인트 서비스계층으로 통합, 개별 트랜잭션 적용, 테스트 코드 개선
  src/main/java/com/example/sinitto/callback/repository/CallbackRepository.java
  src/main/java/com/example/sinitto/callback/service/CallbackService.java
  src/main/java/com/example/sinitto/helloCall/service/HelloCallService.java
  src/main/java/com/example/sinitto/point/service/PointService.java
  src/test/java/com/example/sinitto/callback/repository/CallbackRepositoryTest.java
  src/test/java/com/example/sinitto/callback/service/CallbackServiceTest.java
  src/test/java/com/example/sinitto/hellocall/service/HelloCallServiceTest.java
Labels: ✅ Test Code, ♻️ Refactoring

#157 Deploy: 프론트 배포주소 변경에 따른 상수화값 변경
  src/main/java/com/example/sinitto/auth/service/KakaoApiService.java
  src/test/java/com/example/sinitto/auth/service/KakaoApiServiceTest.java
Labels: 🚀 Deploy

#161 Feat: 카카오메시지 전송 프로토타입 생성 완료
  src/main/java/com/example/sinitto/auth/service/KakaoTokenService.java
  src/main/java/com/example/sinitto/common/properties/KakaoProperties.java
  src/main/java/com/example/sinitto/common/service/KakaoMessageService.java
  src/main/java/com/example/sinitto/point/service/PointAdminService.java
  src/main/java/com/example/sinitto/point/service/PointService.java
  src/test/java/com/example/sinitto/point/service/PointAdminServiceTest.java
  src/test/java/com/example/sinitto/point/service/PointServiceTest.java
Labels: ✨ Feature

#164 HotFix: 카카오메시지 형식 수정 완료
  src/main/java/com/example/sinitto/common/service/KakaoMessageService.java
Labels: 🚑 HotFix!

#168 HotFix : refresh Token 1분 이내에 발급되었을 경우 다시 발급되지 않게 수정
  src/main/java/com/example/sinitto/auth/service/TokenService.java
  src/main/java/com/example/sinitto/common/config/RedisConfig.java
Labels: 🚑 HotFix!

#171 Deploy: DB mysql로 마이그레이션 구현
  .github/workflows/testcode.yml
  build.gradle
  src/main/resources/application.properties
  src/test/java/com/example/sinitto/SinittoApplicationTests.java
  src/test/java/com/example/sinitto/auth/repository/KakaoTokenRepositoryTest.java
  src/test/java/com/example/sinitto/auth/service/KakaoApiServiceTest.java
  src/test/java/com/example/sinitto/auth/service/KakaoTokenServiceTest.java
  src/test/java/com/example/sinitto/auth/service/TokenServiceTest.java
  src/test/java/com/example/sinitto/callback/entity/CallbackTest.java
  src/test/java/com/example/sinitto/callback/repository/CallbackRepositoryTest.java
  src/test/java/com/example/sinitto/callback/service/CallbackServiceTest.java
  src/test/java/com/example/sinitto/guard/repository/SeniorRepositoryTest.java
  src/test/java/com/example/sinitto/guard/service/GuardServiceTest.java
  src/test/java/com/example/sinitto/guardGuideline/repository/GuardGuidelineRepositoryTest.java
  src/test/java/com/example/sinitto/guardGuideline/service/GuardGuildelineServiceTest.java
  src/test/java/com/example/sinitto/hellocall/repository/HelloCallRepositoryTest.java
  src/test/java/com/example/sinitto/hellocall/repository/HelloCallTimeLogRepositoryTest.java
  src/test/java/com/example/sinitto/hellocall/repository/TimeSlotRepositoryTest.java
  src/test/java/com/example/sinitto/member/repository/MemberRepositoryTest.java
  src/test/java/com/example/sinitto/member/service/MemberServiceTest.java
  src/test/java/com/example/sinitto/sinitto/repository/SinittoBankInfoRepositoryTest.java
  src/test/java/com/example/sinitto/sinitto/service/SinittoServiceTest.java
Labels: 🚀 Deploy

#174 HotFix: 테스트 ddl 설정 변경
  .github/workflows/testcode.yml
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
  src/test/java/com/example/sinitto/SinittoApplicationTests.java
  src/test/java/com/example/sinitto/sinitto/repository/SinittoBankInfoRepositoryTest.java
Labels: 🚀 Deploy, 🚑 HotFix!

#175 feat, test : redis 전체 삭제 기능 구현 및 테스트 코드 추가
  src/main/java/com/example/sinitto/auth/controller/AuthController.java
  src/main/java/com/example/sinitto/auth/service/TokenService.java
  src/main/resources/application.properties
  src/test/java/com/example/sinitto/auth/service/TokenServiceTest.java
Labels: ✨ Feature, ✅ Test Code

#166 Fix: 환불하는데 돈이 오히려 차감되던 버그 수정과 시니어 등록, 수정 시 폰 번호 중복 확인 로직 추가
  src/main/java/com/example/sinitto/guard/repository/SeniorRepository.java
  src/main/java/com/example/sinitto/guard/service/GuardService.java
  src/main/java/com/example/sinitto/helloCall/controller/HelloCallController.java
  src/main/java/com/example/sinitto/helloCall/service/HelloCallService.java
  src/main/java/com/example/sinitto/point/service/PointService.java
  src/test/java/com/example/sinitto/guard/service/GuardServiceTest.java
  src/test/java/com/example/sinitto/hellocall/service/HelloCallServiceTest.java
  src/test/java/com/example/sinitto/point/service/PointServiceTest.java
Labels: 😡 Bug Fix, ✨ Feature, ✅ Test Code

#178 HotFix: 로그아웃 시 멤버가 없으면 로그아웃 안되는 에러 해결
  src/main/java/com/example/sinitto/member/service/MemberService.java
  src/test/java/com/example/sinitto/member/service/MemberServiceTest.java
Labels: 🚑 HotFix!

#181 Feat: 시니또 탈퇴 본인이 할당받은 서비스가 있으면 다시 대기상태로 전환되는 로직 추가
  src/main/java/com/example/sinitto/callback/service/CallbackService.java
  src/main/java/com/example/sinitto/helloCall/entity/HelloCall.java
  src/main/java/com/example/sinitto/helloCall/entity/HelloCallTimeLog.java
  src/main/java/com/example/sinitto/helloCall/repository/HelloCallRepository.java
  src/main/java/com/example/sinitto/helloCall/service/HelloCallService.java
  src/main/java/com/example/sinitto/member/service/MemberService.java
  src/test/java/com/example/sinitto/callback/service/CallbackServiceTest.java
  src/test/java/com/example/sinitto/hellocall/service/HelloCallServiceTest.java
  src/test/java/com/example/sinitto/member/service/MemberServiceTest.java
Labels: ✨ Feature

#185 Refactor: 5차 코드리뷰 기반 개편 (안부전화 요일 변환, URL 환경변수화 관련) 구현
  .github/workflows/deploy.yml
  src/main/java/com/example/sinitto/auth/service/KakaoApiService.java
  src/main/java/com/example/sinitto/common/properties/KakaoProperties.java
  src/main/java/com/example/sinitto/common/service/KakaoMessageService.java
  src/main/java/com/example/sinitto/helloCall/service/HelloCallPriceService.java
  src/main/java/com/example/sinitto/point/service/PointService.java
  src/test/java/com/example/sinitto/auth/service/KakaoApiServiceTest.java
Labels: ♻️ Refactoring

#183 HotFix: 시니어 정보 수정 시 전화번호를 수정하지 않고 다른 필드를 수정하면 전화번호 중복 오류가 뜨는 문제 해결
  src/main/java/com/example/sinitto/guard/service/GuardService.java
  src/test/java/com/example/sinitto/guard/service/GuardServiceTest.java
Labels: 🚑 HotFix!

#188 HotFix: 슬랙 웹 훅 URL 환경변수화 과정에서 오류 해결
  .github/workflows/deploy.yml
Labels: 🚑 HotFix!

#190 Deploy: 충전 및 출금 요청 발생시 슬랙메시지 전송 기능 추가
  src/main/java/com/example/sinitto/common/service/SlackMessageService.java
  src/main/java/com/example/sinitto/point/service/PointService.java
  src/test/java/com/example/sinitto/point/service/PointServiceTest.java
Labels: 🚀 Deploy, ✨ Feature

#192 HotFix: 속성 Value를 항상 null로 받는 문제 해결
  .github/workflows/testcode.yml
  src/main/java/com/example/sinitto/common/service/SlackMessageService.java
  src/test/java/com/example/sinitto/SinittoApplicationTests.java
Labels: 🚑 HotFix!

#197 HotFix: 중복 환경변수 이분화
  .github/workflows/testcode.yml
  src/main/java/com/example/sinitto/common/service/SlackMessageService.java
  src/test/java/com/example/sinitto/SinittoApplicationTests.java
Labels: 🚑 HotFix!

#200 Refactor : ArgumentResolver -> Interceptor로 변경
  src/main/java/com/example/sinitto/callback/controller/CallbackController.java
  src/main/java/com/example/sinitto/common/annotation/MemberId.java
  src/main/java/com/example/sinitto/common/config/ArgumentResolverConfig.java
  src/main/java/com/example/sinitto/common/config/WebConfig.java
  src/main/java/com/example/sinitto/common/interceptor/JwtInterceptor.java
  src/main/java/com/example/sinitto/common/resolver/MemberIdArgumentResolver.java
  src/main/java/com/example/sinitto/common/resolver/MemberIdProvider.java
  src/main/java/com/example/sinitto/guard/controller/GuardController.java
  src/main/java/com/example/sinitto/guardGuideline/controller/GuardGuidelineController.java
  src/main/java/com/example/sinitto/helloCall/controller/HelloCallController.java
  src/main/java/com/example/sinitto/member/controller/MemberController.java
  src/main/java/com/example/sinitto/member/service/MemberService.java
  src/main/java/com/example/sinitto/member/service/MemberTokenService.java
  src/main/java/com/example/sinitto/point/controller/PointController.java
  src/main/java/com/example/sinitto/review/controller/ReviewController.java
  src/main/java/com/example/sinitto/sinitto/controller/SinittoController.java
  src/test/java/com/example/sinitto/member/service/MemberServiceTest.java
  src/test/java/com/example/sinitto/member/service/MemberTokenServiceTest.java
Labels: ♻️ Refactoring

#206 Feat: 진행중인(대기상태, 요청상태) 포인트 충전, 출금 요청 존재하면 추가 요청 불가 로직 추가
  src/main/java/com/example/sinitto/point/repository/PointLogRepository.java
  src/main/java/com/example/sinitto/point/service/PointService.java
  src/test/java/com/example/sinitto/point/service/PointServiceTest.java
Labels: ✨ Feature

#205 Feat: 최소 출금 포인트 설정, 첫 가입시 무료 포인트 적립
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
  src/main/java/com/example/sinitto/member/service/MemberService.java
  src/main/java/com/example/sinitto/point/dto/PointLogResponse.java
  src/main/java/com/example/sinitto/point/entity/PointLog.java
  src/main/java/com/example/sinitto/point/service/PointService.java
  src/test/java/com/example/sinitto/member/service/MemberServiceTest.java
  src/test/java/com/example/sinitto/point/entity/PointLogTest.java
  src/test/java/com/example/sinitto/point/service/PointServiceTest.java
Labels: ✨ Feature

#210 HotFix: 포인트 로그 조회에서 content 는 `String` 으로 반환하도록 롤백
  src/main/java/com/example/sinitto/point/dto/PointLogResponse.java
  src/main/java/com/example/sinitto/point/service/PointService.java
Labels: 🚑 HotFix!

#208 Feat: 카카오페이로 송금 카카오메시지에 추가
  src/main/java/com/example/sinitto/common/properties/KakaoProperties.java
  src/main/java/com/example/sinitto/common/service/KakaoMessageService.java
Labels: ✨ Feature

#212 HotFix: 보호자의 회원가입때만 환영 포인트 지급하도록 수정
  src/main/java/com/example/sinitto/member/service/MemberService.java
  src/test/java/com/example/sinitto/member/service/MemberServiceTest.java
Labels: ✨ Feature, 🚑 HotFix!

#215 HotFix: 시니또 가입시 포인트 연관 시키기
  src/main/java/com/example/sinitto/member/service/MemberService.java
  src/test/java/com/example/sinitto/member/service/MemberServiceTest.java
Labels: 😡 Bug Fix

#213 Feat: 관리자 인증 및 인가 기능 구현
  src/main/java/com/example/sinitto/SinittoApplication.java
  src/main/java/com/example/sinitto/auth/controller/AuthController.java
  src/main/java/com/example/sinitto/auth/service/TokenService.java
  src/main/java/com/example/sinitto/common/config/SwaggerConfig.java
  src/main/java/com/example/sinitto/common/config/WebConfig.java
  src/main/java/com/example/sinitto/common/interceptor/JwtInterceptor.java
  src/main/java/com/example/sinitto/common/properties/AdminProperties.java
  src/main/java/com/example/sinitto/common/service/SlackMessageService.java
  src/main/java/com/example/sinitto/guard/service/GuardService.java
  src/main/java/com/example/sinitto/member/controller/MemberAdminController.java
  src/main/java/com/example/sinitto/member/service/MemberTokenService.java
  src/main/java/com/example/sinitto/point/controller/PointAdminController.java
  src/main/java/com/example/sinitto/review/entity/Review.java
  src/main/resources/application.properties
  src/main/resources/static/css/header.css
  src/main/resources/static/css/login.css
  src/main/resources/templates/dummy/login.html
  src/main/resources/templates/point/charge.html
  src/main/resources/templates/point/header.html
  src/main/resources/templates/point/login.html
  src/main/resources/templates/point/withdraw.html
  src/test/java/com/example/sinitto/auth/service/TokenServiceTest.java
Labels: ✨ Feature, ♻️ Refactoring

#221 HotFix: 시니또용 카테고리별 가이드라인 조회 검증 로직 수정
  src/main/java/com/example/sinitto/guardGuideline/service/GuardGuidelineService.java
Labels: 🚑 HotFix!

#219 Refactor: 6차 코드리뷰 반영
  src/main/java/com/example/sinitto/helloCall/service/HelloCallService.java
Labels: ♻️ Refactoring

#223 Feat: 콜백 가이드라인 type 추가
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
  src/main/java/com/example/sinitto/guardGuideline/entity/GuardGuideline.java
  src/main/resources/application.properties
  src/main/resources/templates/dummy/login.html
  src/test/java/com/example/sinitto/guardGuideline/entity/GuardGuidelineTest.java
Labels: ✨ Feature, ✅ Test Code, ♻️ Refactoring

#225 Refactor: 더미데이터 수정 및 Swagger 조회 편의성을 위한 개선
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
  src/main/java/com/example/sinitto/guardGuideline/service/GuardGuidelineService.java
  src/main/resources/static/css/header.css
  src/main/resources/templates/point/login.html
Labels: ♻️ Refactoring

#228 Feat: 배포파일 및 테스트코드 name 분리, 테스트코드 결과 제공, 배포 성공여부 슬랙메세지 전송
  .github/workflows/deploy.yml
  .github/workflows/testcode.yml
Labels: 📖 Docs, ✨ Feature

#230 Fix: 포인트 로그관련 더미데이터 각 유저의 역할에 맞는 로그가 남도록 수정
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
Labels: 🚀 Deploy

#232 Deploy: 더미데이터로의 초기화 방지용 수정
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
Labels: 🚀 Deploy

#235 Feat: 최종프로젝트 심사를 위한 관리자 페이지 계정정보 추가
  src/main/resources/static/css/login.css
  src/main/resources/templates/point/login.html
Labels: ✨ Feature, ♻️ Refactoring

#233 Docs: README.md 작성
  README.md
Labels: 📖 Docs

#236 마지막 산출물용 Pull Request 입니다
  .github/workflows/deploy.yml
  .github/workflows/testcode.yml
  README.md
  src/main/java/com/example/sinitto/SinittoApplication.java
  src/main/java/com/example/sinitto/auth/controller/AuthController.java
  src/main/java/com/example/sinitto/auth/service/TokenService.java
  src/main/java/com/example/sinitto/callback/controller/CallbackController.java
  src/main/java/com/example/sinitto/common/annotation/MemberId.java
  src/main/java/com/example/sinitto/common/config/ArgumentResolverConfig.java
  src/main/java/com/example/sinitto/common/config/SwaggerConfig.java
  src/main/java/com/example/sinitto/common/config/WebConfig.java
  src/main/java/com/example/sinitto/common/dummy/InitialData.java
  src/main/java/com/example/sinitto/common/interceptor/JwtInterceptor.java
  src/main/java/com/example/sinitto/common/properties/AdminProperties.java
  src/main/java/com/example/sinitto/common/properties/KakaoProperties.java
  src/main/java/com/example/sinitto/common/resolver/MemberIdArgumentResolver.java
  src/main/java/com/example/sinitto/common/resolver/MemberIdProvider.java
  src/main/java/com/example/sinitto/common/service/KakaoMessageService.java
  src/main/java/com/example/sinitto/common/service/SlackMessageService.java
  src/main/java/com/example/sinitto/guard/controller/GuardController.java
  src/main/java/com/example/sinitto/guard/service/GuardService.java
  src/main/java/com/example/sinitto/guardGuideline/controller/GuardGuidelineController.java
  src/main/java/com/example/sinitto/guardGuideline/entity/GuardGuideline.java
  src/main/java/com/example/sinitto/guardGuideline/service/GuardGuidelineService.java
  src/main/java/com/example/sinitto/helloCall/controller/HelloCallController.java
  src/main/java/com/example/sinitto/helloCall/service/HelloCallService.java
  src/main/java/com/example/sinitto/member/controller/MemberAdminController.java
  src/main/java/com/example/sinitto/member/controller/MemberController.java
  src/main/java/com/example/sinitto/member/service/MemberService.java
  src/main/java/com/example/sinitto/member/service/MemberTokenService.java
  src/main/java/com/example/sinitto/point/controller/PointAdminController.java
  src/main/java/com/example/sinitto/point/controller/PointController.java
  src/main/java/com/example/sinitto/point/entity/PointLog.java
  src/main/java/com/example/sinitto/point/repository/PointLogRepository.java
  src/main/java/com/example/sinitto/point/service/PointService.java
  src/main/java/com/example/sinitto/review/controller/ReviewController.java
  src/main/java/com/example/sinitto/review/entity/Review.java
  src/main/java/com/example/sinitto/sinitto/controller/SinittoController.java
  src/main/resources/application.properties
  src/main/resources/static/css/header.css
  src/main/resources/static/css/login.css
  src/main/resources/templates/dummy/login.html
  src/main/resources/templates/point/charge.html
  src/main/resources/templates/point/header.html
  src/main/resources/templates/point/login.html
  src/main/resources/templates/point/withdraw.html
  src/test/java/com/example/sinitto/auth/service/TokenServiceTest.java
  src/test/java/com/example/sinitto/guardGuideline/entity/GuardGuidelineTest.java
  src/test/java/com/example/sinitto/member/service/MemberServiceTest.java
  src/test/java/com/example/sinitto/member/service/MemberTokenServiceTest.java
  src/test/java/com/example/sinitto/point/entity/PointLogTest.java
  src/test/java/com/example/sinitto/point/service/PointServiceTest.java
Labels: 🚀 Deploy

#241 Refactor: CORS 프론트 개발환경 추가
  src/main/java/com/example/sinitto/common/config/WebConfig.java
Labels: 🚀 Deploy, ♻️ Refactoring

#243 HotFix: CORS 오류 해결
  src/main/java/com/example/sinitto/common/config/WebConfig.java
Labels: 🚑 HotFix!

#245 Deploy: CORS 요청 메서드 한정
  src/main/java/com/example/sinitto/common/config/WebConfig.java
Labels: 🚀 Deploy

#251 DOCS: 시연영상 리드미에 추가
  README.md
Labels: 📖 Docs
